# Generated by Django 4.0.4 on 2022-06-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NewStoreBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_take', models.DateField()),
                ('avaliable', models.IntegerField(choices=[(0, 'Not Avaliable'), (1, 'Avaliable')], default=1)),
                ('Author', models.ManyToManyField(to='newapp.author')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='per', to='newapp.person')),
            ],
        ),
    ]
